# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMaW3OcIcvrO8N30Z64Da4-DXZGJ2ETZ
"""

! pip install gtts

from gtts import gTTS
import os
text=" 안녕하세요, 저는 정보 시스템 및 기술학과 2학년 학생인 압두나비예바 모히라입니다."
language="ko"
tts=gTTS(text=text, lang=language, slow=False)
audio_file="aytilgan_ko_file.mp3"
tts.save(audio_file)
from IPython.display import Audio
Audio(audio_file)